apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: courts-local-scorecard-prod-ingress
  namespace: courts-local-scorecard-prod
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/set-identifier: courts-local-scorecard-prod-ingress-courts-local-scorecard-prod-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
spec:
  tls:
  - hosts:
    - courts-local-scorecard-prod.apps.live.cloud-platform.service.justice.gov.uk
  rules:
  - host: courts-local-scorecard-prod.apps.live.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: local-scorecard-service
            port:
              number: 8080
