apiVersion: apps/v1
kind: Deployment
metadata:
  name: crown-court-local-scorecard
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: crown-court-local-scorecard
  template:
    metadata:
      labels:
        app: crown-court-local-scorecard
    spec:
      containers:
      - name: local-scorecard
        image: :f9444bcc880151eee9fc711b9c2da21f55d095a2
        ports:
        - containerPort: 8080
