apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: crown-court-local-scorecard-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - crown-court-local-scorecard.apps.live.cloud-platform.service.justice.gov.uk
  rules:
  - host: crown-court-local-scorecard.apps.live.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: rubyapp-service
          servicePort: 4567
