apiVersion: v1
kind: Service
metadata:
  name: local-scorecard-service
  labels:
    app: local-scorecard-service
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  selector:
    app: crown-court-local-scorecard
